// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHoayvYNUzKwSaRUqmyMVwxZKUV4AIsxE',
    appId: '1:1013689779837:web:2b499e3381a63202831314',
    messagingSenderId: '1013689779837',
    projectId: 'practicalmanagementapp',
    authDomain: 'practicalmanagementapp.firebaseapp.com',
    storageBucket: 'practicalmanagementapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72reg8F1TIVA5umjjkArQwvi07NdeDbc',
    appId: '1:1013689779837:android:52f31b3e6695058f831314',
    messagingSenderId: '1013689779837',
    projectId: 'practicalmanagementapp',
    storageBucket: 'practicalmanagementapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeA5ecrN0ocb4PD7XQIBKKbDk5LbNHls',
    appId: '1:1013689779837:ios:48b0d5d16b5331ab831314',
    messagingSenderId: '1013689779837',
    projectId: 'practicalmanagementapp',
    storageBucket: 'practicalmanagementapp.firebasestorage.app',
    iosBundleId: 'com.example.practicalManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNeA5ecrN0ocb4PD7XQIBKKbDk5LbNHls',
    appId: '1:1013689779837:ios:48b0d5d16b5331ab831314',
    messagingSenderId: '1013689779837',
    projectId: 'practicalmanagementapp',
    storageBucket: 'practicalmanagementapp.firebasestorage.app',
    iosBundleId: 'com.example.practicalManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHoayvYNUzKwSaRUqmyMVwxZKUV4AIsxE',
    appId: '1:1013689779837:web:2b499e3381a63202831314',
    messagingSenderId: '1013689779837',
    projectId: 'practicalmanagementapp',
    authDomain: 'practicalmanagementapp.firebaseapp.com',
    storageBucket: 'practicalmanagementapp.firebasestorage.app',
  );
}
